apiVersion: batch/v1
kind: Job
metadata:
  name: s3cphello
  namespace: internal2cdemo
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      labels:
        app: s3cphello
    spec:
      volumes:
      - name: aws-creds-volume
        emptyDir:
          sizeLimit: 1Mi
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: aws-wlinitcontainer
          imagePullPolicy: Always
          image: quay.io/ubyon/sampleapps:aws-wlinitcontainer-0.5
          env:
            - name: CLUSTER_TYPE
              value: "dev"
            - name: UBYON_WORKLOAD_ATTESTOR_HOST_AND_PORT
              value: "ubyon-workload-attestor.internal2cdemo.svc.cluster.local:34323"
            - name: TARGET_APP
              value: "signin.aws.amazon.com"
            - name: OUTPUT_AWS_CREDS_FILE
              value: "/etc/awscreds/credentials"
            - name: EXTRA_TAGS_JSON_ARR
              value: '[{"tag": "csp", "value": "Aws"}, {"tag": "Group", "value": "Storage"}]'
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
               fieldRef:
                 fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: aws-creds-volume
              mountPath: /etc/awscreds
      containers:
      - image: quay.io/ubyon/sampleapps:s3-cphello-1.0
        name: s3cphello
        imagePullPolicy: Always
        env:
          - name: CLUSTER_TYPE
            value: "dev"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
             fieldRef:
               fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: aws-creds-volume
            mountPath: "/root/.aws"
      restartPolicy: Never
      imagePullSecrets:
        - name: ubyon-workload-pull-secret